### ISSUE TITLE
CRUD productos

### ISSUE THREAD

**Issue by andres174** [gabriel12QK/Ecommerce-web#5]
- Formulario de ingreso de productos
- Tabla para visualizar los productos
- Editar datos de un producto
- Eliminar un producto (borrado lógico)

**Comment by bermeo2000** [comment]
Formulario de ingreso de productos
![image](https://user-images.githubusercontent.com/104100468/209011030-a9a33466-7075-4a99-84ac-3a376e8ce239.png)

Tabla para visualizar los productos
![image](https://user-images.githubusercontent.com/104100468/209011163-76dc9563-ad96-49b4-b2d5-c8c02397e1b0.png)

Editar datos de un producto
![image](https://user-images.githubusercontent.com/104100468/209011315-d2e10093-0984-4529-9b14-0f989dba71bb.png)

Eliminar un producto (borrado lógico)
![image](https://user-images.githubusercontent.com/104100468/209011521-f64f5240-d1d2-447c-bc1c-5e998304a744.png)

Sus validaciones requeridas
![image](https://user-images.githubusercontent.com/104100468/209011712-d99ac354-3bb7-40b3-b274-f31f08a101bb.png)
